import './globals.css'
import { Inter } from 'next/font/google'
import { useState, useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const [backgroundColor, setBackgroundColor] = useState('white-background');

  const toggleBackgroundColor = () => {
    setBackgroundColor(prevColor => 
      prevColor === 'white-background' ? 'black-background' : 'white-background'
    );
  };

  useEffect(() => {
    if (document.body.classList.contains('black-background')) {
      setBackgroundColor('black-background');
    } else {
      setBackgroundColor('white-background');
    }
  }, []);

  return (
    <html lang="en">
      <body className={`${inter.className} ${backgroundColor}`} id="root">
        {children}
      </body>
    </html>
  );
}